### ISSUE TITLE
limit zoom level of map ? 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/blurred-location#3]
>  use the module to implement (and document) an option in LBL to limit map input to a
> precision range, with { max: 14, min: 4 } (i.e. the map would not zoom outside that range nor would coordinates generated fall outside that range of precisions)

@jywarren , more details please ? 
Do we need the markers array from LBLD to implement this ?

**Comment by sagarpreet-chadha** [comment]
Kindly confirm this ,
So this function :
1.) restricts the zoom level range .
2.) takes markers array as input , and make sure that these markers shows only between the zoom level range ?

**Comment by jywarren** [comment]
Ah, actually this would be part of LBL, as it's a way to restrict the input
-- the creation of precision data. So 1) is correct, but 2) would just make
it impossible to input a location that has a precision outside the given
range. Make sense? Thanks! You could probably transfer this issue over to
LBL!
