### ISSUE TITLE
Add convertor functions 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/blurred-location#4]
> can we have a pair of converters like BL.distanceToPrecision(meters, latitude) and BL.precisionToDistance(decimals, latitude)? If no latitude is specified, we could output a message explaining how precision changes with latitude, and mentioning the latitudes of two cities with very different values?

Hi @jywarren , how to implement this ?

What does distance here refers to ? Thanks 😄 !

**Comment by jywarren** [comment]
So, it would accept a distance in meters, and output a precision (say, 0.01
or 0.001... however we want to represent precision values?)

**Comment by sagarpreet-chadha** [comment]
Okay so we input the latitude and the distance in meters from that latitude line ?
And we output the precision one should give to the coordinates so that given distance is covered by the bounding square ?

**Comment by jywarren** [comment]
Ah, ok, i think we have to make this more clear. I see what you're doing in #6 and that does make sense. However, the idea is not to take the number of decimal places as the precision, but to try to quantify how big a grid square is at the given precision. So for `latitude` with 2 decimal places, like `14.04`, that'd be x meters by y meters wide. 

But there's some ambiguity -- should we use just the latitude, and rename this method? That makes it less useful, maybe. Or should we say something like `the precision you should choose so people would be able to find your location to within X meters` -- and how would we write that as a simple function name?

Thank you for helping me to figure out that this is more complicated than it seems! What do you think?
